In [2]:
import pandas as pd

- Đọc bộ dữ liệu, cho biết số dòng, số cột và kiểu dữ liệu của các thuộc tính.

In [3]:
# Đọc dữ liệu
df = pd.read_csv("OnlineRetail.csv", encoding = "ISO-8859-1")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
# Số dòng
df.shape[0]

541909

In [5]:
# Số cột
df.shape[1]

8

In [6]:
# Kiểu dữ liệu của các thuộc tính
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

- Xây dựng bảng Pivot table, với mỗi Số hóa đơn tính trung bình cộng số lượng các mặt hàng theo từng Quốc gia.

In [7]:
df.pivot_table(values = "Quantity", index = "InvoiceNo", columns = "Country", aggfunc = "mean")

Country,Australia,Austria,Bahrain,Belgium,Brazil,Canada,Channel Islands,Cyprus,Czech Republic,Denmark,...,RSA,Saudi Arabia,Singapore,Spain,Sweden,Switzerland,USA,United Arab Emirates,United Kingdom,Unspecified
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.714286,NaN
536366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN
536367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.916667,NaN
536368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.750000,NaN
536369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C581484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80995.000000,NaN
C581490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.500000,NaN
C581499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN
C581568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.000000,NaN
C581569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.000000,NaN

- Xây dựng bảng Pivot table, với mỗi khách hàng cho biết số lượng mua hàng lớn nhất và nhỏ nhất theo kho.

In [8]:
df.pivot_table(values = "Quantity", index = "StockCode", columns = "CustomerID", aggfunc = {min, max})

               max                                                          \
CustomerID 12346.0 12347.0 12348.0 12349.0 12350.0 12352.0 12353.0 12354.0
StockCode
10002          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
10080          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
10120          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
10123C         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
10124A         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
...            ...     ...     ...     ...     ...     ...     ...     ...
D              NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
DOT            NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
M              NaN     NaN     NaN     NaN     NaN     1.0     NaN     NaN
PADS           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
POST           NaN     NaN     6.0     1.0     1.0     2.0     NaN     NaN

                            ...     min                                  \
CustomerID 12355.0 12356.0  ... 18273.0 18274.0 18276.0 18277.0 18278.0
StockCode                   ...
10002          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
10080          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
10120          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
10123C         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
10124A         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
...            ...     ...  ...     ...     ...     ...     ...     ...
D              NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
DOT            NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
M              NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
PADS           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
POST           NaN    18.0  ...     NaN     NaN     NaN     NaN     NaN


CustomerID 18280.0 18281.0 18282.0 18283.0 18287.0
StockCode
10002          NaN     NaN     NaN     NaN     NaN
10080          NaN     NaN     NaN     NaN     NaN
10120          NaN     NaN     NaN     NaN     NaN
10123C         NaN     NaN     NaN     NaN     NaN
10124A         NaN     NaN     NaN     NaN     NaN
...            ...     ...     ...     ...     ...
D              NaN     NaN     NaN     NaN     NaN
DOT            NaN     NaN     NaN     NaN     NaN
M              NaN     NaN     NaN     1.0     NaN
PADS           NaN     NaN     NaN     NaN     NaN
POST           NaN     NaN     NaN     NaN     NaN

[3684 rows x 8744 columns]

- Xây dựng bảng Pivot table, với mỗi Mã kho tính tổng số lượng các mặt hàng và trung bình cộng giá.

In [9]:
import numpy as np

In [10]:
df.pivot_table(values = ["Quantity", "UnitPrice"], index = "InvoiceNo", columns = "StockCode", aggfunc = {"Quantity": np.sum, "UnitPrice": np.mean})

MemoryError: Unable to allocate 1.57 GiB for an array with shape (8140, 25900) and data type float64

- Xây dựng bảng Pivot table cho biết tổng số lượng hàng bán được mỗi ngày

In [11]:
df.pivot_table(values = "Quantity", index = "InvoiceDate", aggfunc = {"Quantity": np.sum})

                 Quantity
InvoiceDate
1/10/2011 10:04       -29
1/10/2011 10:07        -4
1/10/2011 10:08       -14
1/10/2011 10:32       260
1/10/2011 10:35       408
...                   ...
9/9/2011 8:48         104
9/9/2011 9:03         105
9/9/2011 9:13         372
9/9/2011 9:38         203
9/9/2011 9:52         782

[23260 rows x 1 columns]